FROM ghcr.io/ublue-os/bazzite-gnome:testing

RUN --mount=type=tmpfs,dst=/tmp \
    dnf5 -y --setopt=install_weak_deps=False install nodejs-npm && \
    git clone https://github.com/UbayGD/reboottouefi /tmp/reboottouefi && \
    rm -rf /usr/share/gnome-shell/extensions/reboottouefi@ubaygd.com && \
    env HOME=/tmp make -C /tmp/reboottouefi pack && \
    unzip -o /tmp/reboottouefi/reboottouefi@ubaygd.com-*.zip -d /usr/share/gnome-shell/extensions/reboottouefi@ubaygd.com && \
    dnf5 -y remove nodejs-npm && \
    dnf5 clean all && \
    mv /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/po /usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/locale && \
    mv /usr/share/gnome-shell/extensions/logomenu@aryan_k/po /usr/share/gnome-shell/extensions/logomenu@aryan_k/locale && \
    mv /usr/share/gnome-shell/extensions/caffeine@patapon.info/po /usr/share/gnome-shell/extensions/caffeine@patapon.info/locale
